name: wa-track

services:
  - name: api
    environment_slug: node-js
    source_dir: apps/api
    http_port: 8080
    build_command: npm ci && npm run build
    run_command: node dist/server.js
    routes:
      - path: /
    git:
      repo_clone_url: https://github.com/StonerStyle/wa-track_0.1.git
      branch: main
    envs:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APP_ORIGIN
        scope: RUN_TIME
        type: GENERAL
      - key: NODE_VERSION
        value: "18"
        scope: BUILD_TIME

  - name: worker
    environment_slug: node-js
    source_dir: apps/worker
    http_port: 8080
    build_command: npm ci && npm run build
    run_command: node dist/index.js
    git:
      repo_clone_url: https://github.com/StonerStyle/wa-track_0.1.git
      branch: main
    envs:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NODE_VERSION
        value: "18"
        scope: BUILD_TIME
